In [32]:
from docling.document_converter import DocumentConverter

converter = DocumentConverter()

result = converter.convert(
    "./files/1-s2.0-S0022309324001145-main.pdf"
)

doc = result.document

/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [39]:
from docling_core.types.doc import TableItem

for item, _ in doc.iterate_items():
    if isinstance(item, TableItem):
        print(item)

self_ref='#/tables/0' parent=RefItem(cref='#/body') children=[RefItem(cref='#/texts/194')] content_layer=<ContentLayer.BODY: 'body'> label=<DocItemLabel.TABLE: 'table'> prov=[ProvenanceItem(page_no=6, bbox=BoundingBox(l=36.855796813964844, t=126.841796875, r=558.0357666015625, b=52.7877197265625, coord_origin=<CoordOrigin.BOTTOMLEFT: 'BOTTOMLEFT'>), charspan=(0, 0))] captions=[RefItem(cref='#/texts/194')] references=[] footnotes=[] image=None data=TableData(table_cells=[TableCell(bbox=BoundingBox(l=43.597, t=671.9549890000001, r=58.242, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=0, end_col_offset_idx=1, text='Glass ID', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.461, t=671.9549890000001, r=99.024, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=1, end_col_offset_idx=2, text='Tg( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.514, t=671.9549890000001, r=156.268, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=2, end_col_offset_idx=3, text='Ts( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.568, t=671.9549890000001, r=214.755, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=3, end_col_offset_idx=4, text='Tc( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.62, t=671.9549890000001, r=273.401, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=4, end_col_offset_idx=5, text='Tp( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.618, t=671.9549890000001, r=342.811, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=2, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=5, end_col_offset_idx=7, text='Density (g/cm 3)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.044, t=671.9549890000001, r=459.578, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=2, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=7, end_col_offset_idx=9, text='CTE (30~600 ◦ C) ( × 10 GLYPH<0> 6 K GLYPH<0> 1)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=685.1079890000001, r=348.13, b=690.955989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=1, end_row_offset_idx=2, start_col_offset_idx=5, end_col_offset_idx=6, text='Annealed glass', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=685.1079890000001, r=425.26, b=690.955989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=1, end_row_offset_idx=2, start_col_offset_idx=6, end_col_offset_idx=7, text='Glass-ceramic', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=685.1079890000001, r=474.553, b=690.955989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=1, end_row_offset_idx=2, start_col_offset_idx=7, end_col_offset_idx=8, text='Annealed glass', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=685.1079890000001, r=551.684, b=690.955989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=1, end_row_offset_idx=2, start_col_offset_idx=8, end_col_offset_idx=9, text='Glass-ceramic', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=43.6, t=698.259989, r=56.493, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=0, end_col_offset_idx=1, text='La-1', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.464, t=698.259989, r=100.692, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=1, end_col_offset_idx=2, text='641 ± 1.2', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.517, t=698.259989, r=164.516, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=2, end_col_offset_idx=3, text='671.1 ± 1.1', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.57, t=698.259989, r=222.568, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=3, end_col_offset_idx=4, text='783.7 ± 1.6', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.623, t=698.259989, r=280.621, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=4, end_col_offset_idx=5, text='811.1 ± 1.7', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=698.259989, r=334.874, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=5, end_col_offset_idx=6, text='3.97', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=698.259989, r=399.673, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=6, end_col_offset_idx=7, text='3.83', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=698.259989, r=465.04, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=7, end_col_offset_idx=8, text='11.37', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=698.259989, r=529.84, b=704.1089890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=2, end_row_offset_idx=3, start_col_offset_idx=8, end_col_offset_idx=9, text='12.35', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=43.6, t=706.820989, r=56.493, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=0, end_col_offset_idx=1, text='La-2', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.464, t=706.820989, r=106.462, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=1, end_col_offset_idx=2, text='655.1 ± 1.0', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.517, t=706.820989, r=164.516, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=2, end_col_offset_idx=3, text='675.3 ± 1.3', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.57, t=706.820989, r=222.568, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=3, end_col_offset_idx=4, text='817.7 ± 1.2', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.623, t=706.820989, r=280.621, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=4, end_col_offset_idx=5, text='861.7 ± 1.5', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=706.820989, r=334.874, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=5, end_col_offset_idx=6, text='4.08', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=706.820989, r=399.673, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=6, end_col_offset_idx=7, text='3.78', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=706.820989, r=465.04, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=7, end_col_offset_idx=8, text='11.31', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=706.820989, r=529.84, b=712.668989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=3, end_row_offset_idx=4, start_col_offset_idx=8, end_col_offset_idx=9, text='13.05', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=43.6, t=715.380989, r=56.493, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=0, end_col_offset_idx=1, text='La-3', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.464, t=715.380989, r=106.462, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=1, end_col_offset_idx=2, text='668.9 ± 1.4', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.517, t=715.380989, r=164.516, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=2, end_col_offset_idx=3, text='696.7 ± 1.5', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.57, t=715.380989, r=222.568, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=3, end_col_offset_idx=4, text='808.1 ± 1.4', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.623, t=715.380989, r=280.621, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=4, end_col_offset_idx=5, text='836.3 ± 1.9', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=715.380989, r=334.874, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=5, end_col_offset_idx=6, text='4.19', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=715.380989, r=399.673, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=6, end_col_offset_idx=7, text='4.07', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=715.380989, r=465.04, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=7, end_col_offset_idx=8, text='11.24', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=715.380989, r=529.84, b=721.229989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=4, end_row_offset_idx=5, start_col_offset_idx=8, end_col_offset_idx=9, text='12.29', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=43.6, t=723.9409890000001, r=56.493, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=0, end_col_offset_idx=1, text='La-4', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.464, t=723.9409890000001, r=106.462, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=1, end_col_offset_idx=2, text='690.2 ± 1.0', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.517, t=723.9409890000001, r=164.516, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=2, end_col_offset_idx=3, text='715.8 ± 0.8', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.57, t=723.9409890000001, r=222.568, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=3, end_col_offset_idx=4, text='793.9 ± 1.1', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.623, t=723.9409890000001, r=280.621, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=4, end_col_offset_idx=5, text='809.8 ± 1.2', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=723.9409890000001, r=334.874, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=5, end_col_offset_idx=6, text='4.31', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=723.9409890000001, r=399.673, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=6, end_col_offset_idx=7, text='4.22', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=723.9409890000001, r=465.04, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=7, end_col_offset_idx=8, text='11.15', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=723.9409890000001, r=529.84, b=729.7899890000001, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=5, end_row_offset_idx=6, start_col_offset_idx=8, end_col_offset_idx=9, text='12.01', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=43.6, t=732.558989, r=56.493, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=0, end_col_offset_idx=1, text='La-5', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.464, t=732.558989, r=106.462, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=1, end_col_offset_idx=2, text='702.4 ± 1.5', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.517, t=732.558989, r=164.516, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=2, end_col_offset_idx=3, text='726.3 ± 1.1', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.57, t=732.558989, r=222.568, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=3, end_col_offset_idx=4, text='766.4 ± 1.3', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.623, t=732.558989, r=280.621, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=4, end_col_offset_idx=5, text='777.2 ± 0.9', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=321.619, t=732.558989, r=334.874, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=5, end_col_offset_idx=6, text='4.42', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=386.418, t=732.558989, r=399.673, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=6, end_col_offset_idx=7, text='4.30', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=448.042, t=732.558989, r=465.04, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=7, end_col_offset_idx=8, text='10.87', column_header=False, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=512.842, t=732.558989, r=529.84, b=738.407989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=6, end_row_offset_idx=7, start_col_offset_idx=8, end_col_offset_idx=9, text='11.75', column_header=False, row_header=False, row_section=False)], num_rows=7, num_cols=9, grid=[[TableCell(bbox=BoundingBox(l=43.597, t=671.9549890000001, r=58.242, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=0, end_col_offset_idx=1, text='Glass ID', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=89.461, t=671.9549890000001, r=99.024, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=1, end_col_offset_idx=2, text='Tg( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=147.514, t=671.9549890000001, r=156.268, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=2, end_col_offset_idx=3, text='Ts( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=205.568, t=671.9549890000001, r=214.755, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_col_offset_idx=3, end_col_offset_idx=4, text='Tc( ◦ C)', column_header=True, row_header=False, row_section=False), TableCell(bbox=BoundingBox(l=263.62, t=671.9549890000001, r=273.401, b=677.802989, coord_origin=<CoordOrigin.TOPLEFT: 'TOPLEFT'>), row_span=1, col_span=1, start_row_offset_idx=0, end_row_offset_idx=1, start_

In [43]:
from docling_core.types.doc import TableItem

for item, _ in doc.iterate_items():
    if isinstance(item, TableItem):

        df = item.export_to_dataframe()

        display(df)

        table = df.values.tolist()

        print(table)

,Glass ID.,Tg( ◦ C).,Ts( ◦ C).,Tc( ◦ C).,Tp( ◦ C).,Density (g/cm 3).Annealed glass,Density (g/cm 3).Glass-ceramic,CTE (30~600 ◦ C) ( × 10 GLYPH<0> 6 K GLYPH<0> 1).Annealed glass,CTE (30~600 ◦ C) ( × 10 GLYPH<0> 6 K GLYPH<0> 1).Glass-ceramic
0,La-1,641 ± 1.2,671.1 ± 1.1,783.7 ± 1.6,811.1 ± 1.7,3.97,3.83,11.37,12.35
1,La-2,655.1 ± 1.0,675.3 ± 1.3,817.7 ± 1.2,861.7 ± 1.5,4.08,3.78,11.31,13.05
2,La-3,668.9 ± 1.4,696.7 ± 1.5,808.1 ± 1.4,836.3 ± 1.9,4.19,4.07,11.24,12.29
3,La-4,690.2 ± 1.0,715.8 ± 0.8,793.9 ± 1.1,809.8 ± 1.2,4.31,4.22,11.15,12.01
4,La-5,702.4 ± 1.5,726.3 ± 1.1,766.4 ± 1.3,777.2 ± 0.9,4.42,4.30,10.87,11.75

[['La-1', '641 ± 1.2', '671.1 ± 1.1', '783.7 ± 1.6', '811.1 ± 1.7', '3.97', '3.83', '11.37', '12.35'], ['La-2', '655.1 ± 1.0', '675.3 ± 1.3', '817.7 ± 1.2', '861.7 ± 1.5', '4.08', '3.78', '11.31', '13.05'], ['La-3', '668.9 ± 1.4', '696.7 ± 1.5', '808.1 ± 1.4', '836.3 ± 1.9', '4.19', '4.07', '11.24', '12.29'], ['La-4', '690.2 ± 1.0', '715.8 ± 0.8', '793.9 ± 1.1', '809.8 ± 1.2', '4.31', '4.22', '11.15', '12.01'], ['La-5', '702.4 ± 1.5', '726.3 ± 1.1', '766.4 ± 1.3', '777.2 ± 0.9', '4.42', '4.30', '10.87', '11.75']]

,Number.,Element proportion (mol%).Ba,Element proportion (mol%).Si,Element proportion (mol%).O,Element proportion (mol%).La,Element proportion (mol%).Ca,Element proportion (mol%).Al,Element proportion (mol%).B,Phase.
0,Point1,19.26,18.86,53.95,0.89,2.35,2.39,2.30,BaSiO 3
1,Point2,29.49,13.19,37.63,1.37,8.51,6.49,3.32,Residual glass phase
2,Point3,7.10,14.64,61.32,13.52,1.05,1.75,0.62,Ba 3 La 6 (SiO 4 ) 6

[['Point1', '19.26', '18.86', '53.95', '0.89', '2.35', '2.39', '2.30', 'BaSiO 3'], ['Point2', '29.49', '13.19', '37.63', '1.37', '8.51', '6.49', '3.32', 'Residual glass phase'], ['Point3', '7.10', '14.64', '61.32', '13.52', '1.05', '1.75', '0.62', 'Ba 3 La 6 (SiO 4 ) 6']]

,Temperature.,Glass-ceramic Number ( Ω • cm).La-1,Glass-ceramic Number ( Ω • cm).La-2,Glass-ceramic Number ( Ω • cm).La-3,Glass-ceramic Number ( Ω • cm).La-4,Glass-ceramic Number ( Ω • cm).La-5
0,650 ◦ C,2.13 £ 10 6,1.50 £ 10 6,1.72 £ 10 6,2.73 £ 10 6,2.83 £ 10 6
1,700 ◦ C,1.02 £ 10 6,6.79 £ 10 5,6.21 £ 10 5,9.79 £ 10 5,1.05 £ 10 6
2,750 ◦ C,3.83 £ 10 5,2.84 £ 10 5,2.05 £ 10 5,3.62 £ 10 5,4.05 £ 10 5
3,800 ◦ C,6.81 £ 10 4,4.57 £ 10 4,3.69 £ 10 4,1.07 £ 10 5,1.63 £ 10 5

[['650 ◦ C', '2.13 £ 10 6', '1.50 £ 10 6', '1.72 £ 10 6', '2.73 £ 10 6', '2.83 £ 10 6'], ['700 ◦ C', '1.02 £ 10 6', '6.79 £ 10 5', '6.21 £ 10 5', '9.79 £ 10 5', '1.05 £ 10 6'], ['750 ◦ C', '3.83 £ 10 5', '2.84 £ 10 5', '2.05 £ 10 5', '3.62 £ 10 5', '4.05 £ 10 5'], ['800 ◦ C', '6.81 £ 10 4', '4.57 £ 10 4', '3.69 £ 10 4', '1.07 £ 10 5', '1.63 £ 10 5']]

In [44]:
from docling.document_converter import DocumentConverter

converter = DocumentConverter()

result = converter.convert(
    "./files/1-s2.0-S002230932500451X-main.pdf"
)

doc = result.document

/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/mohdzaki/anaconda3/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [45]:
from docling_core.types.doc import TableItem

for item, _ in doc.iterate_items():
    if isinstance(item, TableItem):

        df = item.export_to_dataframe()

        display(df)

        table = df.values.tolist()

        print(table)

,Sample.,M (g/ mol).,V m (cm 3 / mol).,V O (cm 3 / mol).,OPD (g atm/l).,E U (eV).,E g (eV).Direct,E g (eV).Indirect
0,TZTi,143.88,26.31,14.22,70.32,0.107,2.979,2.843
1,TZGe,145.12,26.33,14.23,70.27,0.1500,3.331,3.163
2,TZW,151.48,27.14,14.29,70.04,0.129,3.132,2.973
3,TZNb,153.18,27.82,13.91,71.89,0.136,3.193,3.043

[['TZTi', '143.88', '26.31', '14.22', '70.32', '0.107', '2.979', '2.843'], ['TZGe', '145.12', '26.33', '14.23', '70.27', '0.1500', '3.331', '3.163'], ['TZW', '151.48', '27.14', '14.29', '70.04', '0.129', '3.132', '2.973'], ['TZNb', '153.18', '27.82', '13.91', '71.89', '0.136', '3.193', '3.043']]

,Vibrational Mode Assignment,Raman bands (cm GLYPH<0> 1 ),Reference
0,Tellurite Network Vibrations Stretching and Be...,≈ 450,"[55,52]"
1,Vibration of the continuous network comprised ...,≈ 661,[55]
2,Stretching vibrations between tellurium and NB...,≈ 716,"[55,56]"
3,Continuous network vibration of TeO 4 and a Te...,≈ 775,"[55,57]"
4,MO Network Vibrations Asymmetric stretching of...,≈ 820,[55]
5,"Vibrations in [TiO x ] ( x = 5, 6) units",≈ 810,[59]
6,Stretching in distorted [NbO 6 ] units,≈ 890,[55]
7,Stretching of terminal W = O bonds,≈ 925,[56]

[['Tellurite Network Vibrations Stretching and Bending vibration of O Te - O linkages', '≈ 450', '[55,52]'], ['Vibration of the continuous network comprised of TeO 4', '≈ 661', '[55]'], ['Stretching vibrations between tellurium and NBOs atoms', '≈ 716', '[55,56]'], ['Continuous network vibration of TeO 4 and a TeO GLYPH<0> stretching', '≈ 775', '[55,57]'], ['MO Network Vibrations Asymmetric stretching of O-Ge-O in tetrahedral GeO 4', '≈ 820', '[55]'], ['Vibrations in [TiO x ] ( x = 5, 6) units', '≈ 810', '[59]'], ['Stretching in distorted [NbO 6 ] units', '≈ 890', '[55]'], ['Stretching of terminal W = O bonds', '≈ 925', '[56]']]

,Photon energy (MeV)..,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZGe.Geant4,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZGe.XCOM,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZGe.RD %,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZNb.Geant4,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZNb.XCOM,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 ).TZNb.RD %,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 )..Geant4,TZTi..XCOM,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 )..RD %,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 )..Geant4,TZW..XCOM,Mass attenuation coefficient (cm 2 g GLYPH<0> 1 )..RD %
0,0.015,44.4217,45.8100,GLYPH<0> 3.0306,42.7501,43.5700,GLYPH<0> 1.8818,41.3050,43.7200,GLYPH<0> 5.5238,47.0212,48.1300,GLYPH<0> 2.3038
1,0.02,19.9973,21.1000,GLYPH<0> 5.2261,21.3200,22.3300,GLYPH<0> 4.5231,19.3758,20.1100,GLYPH<0> 3.6508,22.2110,22.2300,GLYPH<0> 0.0855
2,0.03,6.9891,7.0510,GLYPH<0> 0.8779,6.9542,7.5020,GLYPH<0> 7.3021,6.4628,6.7220,GLYPH<0> 3.8558,7.4342,7.4700,GLYPH<0> 0.4792
3,0.04,13.9950,14.1200,GLYPH<0> 0.8853,14.7900,14.3300,3.2101,15.0590,13.9700,7.7955,14.2210,14.3300,GLYPH<0> 0.7606
4,0.05,7.8290,7.8310,GLYPH<0> 0.0255,8.3220,7.9480,4.7056,8.4038,7.7530,8.3936,8.2975,7.9500,4.3707
5,0.06,5.1212,4.8240,6.1609,5.1211,4.8950,4.6190,5.1936,4.7780,8.6979,5.1076,4.9010,4.2170
6,0.08,2.3101,2.2500,2.6711,2.3140,2.2820,1.4023,2.4148,2.2300,8.2887,2.7605,2.5260,1.3650
7,0.1,1.3122,1.2630,3.8955,1.3721,1.2800,7.1953,1.3512,1.2530,7.8360,1.5482,1.4190,2.0619
8,0.15,0.4909,0.4801,2.2495,0.4721,0.4855,GLYPH<0> 2.7600,0.5094,0.4771,6.7632,0.5771,0.5335,4.4195
9,0.2,0.2688,0.2699,GLYPH<0> 0.4076,0.2542,0.2723,GLYPH<0> 6.6471,0.2831,0.2687,5.3599,0.3146,0.2947,3.3709
10,0.3,0.1495,0.1470,1.7007,0.1393,0.1478,GLYPH<0> 5.7510,0.1501,0.1467,2.3047,0.1613,0.1554,3.8108
11,0.4,0.1109,0.1088,1.9302,0.1121,0.1091,2.7498,0.1100,0.1087,1.1619,0.1141,0.1127,1.2556
12,0.5,0.0930,0.0906,2.6487,0.0919,0.0908,1.2222,0.0918,0.0906,1.2724,0.0949,0.0928,2.3257
13,0.6,0.0802,0.0797,0.5268,0.0753,0.0799,GLYPH<0> 5.6968,0.0797,0.0798,GLYPH<0> 0.1040,0.0815,0.0811,0.5316
14,0.662,0.0750,0.0748,0.2808,0.0751,0.0749,0.2937,0.0750,0.0749,0.1189,0.0763,0.0758,0.6027
15,0.8,0.0669,0.0666,0.5555,0.0626,0.0667,GLYPH<0> 6.0738,0.0661,0.0667,GLYPH<0> 0.8607,0.0674,0.0672,0.1815
16,1,0.0583,0.0585,GLYPH<0> 0.2736,0.0582,0.0585,GLYPH<0> 0.5467,0.0585,0.0586,GLYPH<0> 0.1742,0.0587,0.0588,GLYPH<0> 0.1088
17,1.173,0.0524,0.0534,GLYPH<0> 1.8529,0.0530,0.0535,GLYPH<0> 0.9540,0.0534,0.0535,GLYPH<0> 0.2616,0.0534,0.0536,GLYPH<0> 0.4495
18,1.332,0.0488,0.0499,GLYPH<0> 2.2249,0.0487,0.0499,GLYPH<0> 2.5040,0.0493,0.0500,GLYPH<0> 1.3668,0.0499,0.0500,GLYPH<0> 0.2079
19,1.5,0.0470,0.0470,0.1064,0.0469,0.0470,GLYPH<0> 0.0425,0.0470,0.0471,GLYPH<0> 0.0383,0.0472,0.0471,0.1826
20,2,0.0411,0.0413,GLYPH<0> 0.4599,0.0413,0.0414,GLYPH<0> 0.1935,0.0417,0.0414,0.8462,0.0417,0.0414,0.6396
21,3,0.0355,0.0361,GLYPH<0> 1.5257,0.0333,0.0361,GLYPH<0> 7.6454,0.0359,0.0361,GLYPH<0> 0.5160,0.0358,0.0363,GLYPH<0> 1.1500
22,4,0.0343,0.0339,1.1799,0.0341,0.0340,0.3826,0.0337,0.0339,GLYPH<0> 0.5257,0.0344,0.0342,0.4999
23,5,0.0331,0.0330,0.1818,0.0310,0.0331,GLYPH<0> 6.3123,0.0327,0.0329,GLYPH<0> 0.8288,0.0336,0.0334,0.5088
24,6,0.0330,0.0327,0.9471,0.0331,0.0328,0.7004,0.0328,0.0326,0.4842,0.0334,0.0332,1.4496
25,8,0.0339,0.0331,2.4501,0.0330,0.0332,GLYPH<0> 0.5723,0.0336,0.0329,2.2151,0.0340,0.0336,1.0850
26,9,0.0337,0.0334,0.8373,0.0343,0.0336,2.0833,0.0336,0.0333,1.0126,0.0345,0.0341,1.2353
27,10,0.0342,0.0339,0.8850,0.0346,0.0341,1.6143,0.0340,0.0337,0.6702,0.0349,0.0346,0.9023
28,12,,,0.2292,0.0352,0.0351,0.2849,,0.0347,1.9741,0.0365,0.0357,2.4215
29,,0.0350,0.0349,,,,,0.0354,,,,,
30,13,0.0356,0.0354,0.3952,0.0358,0.0356,0.4210,0.0359,0.0352,1.8631,,0.0362,
31,14 15,0.0368 0.0371,0.0359 0.0365,2.4207 1.6735,0.0371 0.0369,0.0362 0.0367,2.6279 0.6819,0.0362 0.0367,0.0357 0.0362,1.4646 1.2680,0.0369 0.0373 0.0379,0.0368 0.0373,2.0392 1.4624 1.5671

[['0.015', '44.4217', '45.8100', 'GLYPH<0> 3.0306', '42.7501', '43.5700', 'GLYPH<0> 1.8818', '41.3050', '43.7200', 'GLYPH<0> 5.5238', '47.0212', '48.1300', 'GLYPH<0> 2.3038'], ['0.02', '19.9973', '21.1000', 'GLYPH<0> 5.2261', '21.3200', '22.3300', 'GLYPH<0> 4.5231', '19.3758', '20.1100', 'GLYPH<0> 3.6508', '22.2110', '22.2300', 'GLYPH<0> 0.0855'], ['0.03', '6.9891', '7.0510', 'GLYPH<0> 0.8779', '6.9542', '7.5020', 'GLYPH<0> 7.3021', '6.4628', '6.7220', 'GLYPH<0> 3.8558', '7.4342', '7.4700', 'GLYPH<0> 0.4792'], ['0.04', '13.9950', '14.1200', 'GLYPH<0> 0.8853', '14.7900', '14.3300', '3.2101', '15.0590', '13.9700', '7.7955', '14.2210', '14.3300', 'GLYPH<0> 0.7606'], ['0.05', '7.8290', '7.8310', 'GLYPH<0> 0.0255', '8.3220', '7.9480', '4.7056', '8.4038', '7.7530', '8.3936', '8.2975', '7.9500', '4.3707'], ['0.06', '5.1212', '4.8240', '6.1609', '5.1211', '4.8950', '4.6190', '5.1936', '4.7780', '8.6979', '5.1076', '4.9010', '4.2170'], ['0.08', '2.3101', '2.2500', '2.6711', '2.3140', '2.2820', '1.4023', '2.4148', '2.2300', '8.2887', '2.7605', '2.5260', '1.3650'], ['0.1', '1.3122', '1.2630', '3.8955', '1.3721', '1.2800', '7.1953', '1.3512', '1.2530', '7.8360', '1.5482', '1.4190', '2.0619'], ['0.15', '0.4909', '0.4801', '2.2495', '0.4721', '0.4855', 'GLYPH<0> 2.7600', '0.5094', '0.4771', '6.7632', '0.5771', '0.5335', '4.4195'], ['0.2', '0.2688', '0.2699', 'GLYPH<0> 0.4076', '0.2542', '0.2723', 'GLYPH<0> 6.6471', '0.2831', '0.2687', '5.3599', '0.3146', '0.2947', '3.3709'], ['0.3', '0.1495', '0.1470', '1.7007', '0.1393', '0.1478', 'GLYPH<0> 5.7510', '0.1501', '0.1467', '2.3047', '0.1613', '0.1554', '3.8108'], ['0.4', '0.1109', '0.1088', '1.9302', '0.1121', '0.1091', '2.7498', '0.1100', '0.1087', '1.1619', '0.1141', '0.1127', '1.2556'], ['0.5', '0.0930', '0.0906', '2.6487', '0.0919', '0.0908', '1.2222', '0.0918', '0.0906', '1.2724', '0.0949', '0.0928', '2.3257'], ['0.6', '0.0802', '0.0797', '0.5268', '0.0753', '0.0799', 'GLYPH<0> 5.6968', '0.0797', '0.0798', 'GLYPH<0> 0.1040', '0.0815', '0.0811', '0.5316'], ['0.662', '0.0750', '0.0748', '0.2808', '0.0751', '0.0749', '0.2937', '0.0750', '0.0749', '0.1189', '0.0763', '0.0758', '0.6027'], ['0.8', '0.0669', '0.0666', '0.5555', '0.0626', '0.0667', 'GLYPH<0> 6.0738', '0.0661', '0.0667', 'GLYPH<0> 0.8607', '0.0674', '0.0672', '0.1815'], ['1', '0.0583', '0.0585', 'GLYPH<0> 0.2736', '0.0582', '0.0585', 'GLYPH<0> 0.5467', '0.0585', '0.0586', 'GLYPH<0> 0.1742', '0.0587', '0.0588', 'GLYPH<0> 0.1088'], ['1.173', '0.0524', '0.0534', 'GLYPH<0> 1.8529', '0.0530', '0.0535', 'GLYPH<0> 0.9540', '0.0534', '0.0535', 'GLYPH<0> 0.2616', '0.0534', '0.0536', 'GLYPH<0> 0.4495'], ['1.332', '0.0488', '0.0499', 'GLYPH<0> 2.2249', '0.0487', '0.0499', 'GLYPH<0> 2.5040', '0.0493', '0.0500', 'GLYPH<0> 1.3668', '0.0499', '0.0500', 'GLYPH<0> 0.2079'], ['1.5', '0.0470', '0.0470', '0.1064', '0.0469', '0.0470', 'GLYPH<0> 0.0425', '0.0470', '0.0471', 'GLYPH<0> 0.0383', '0.0472', '0.0471', '0.1826'], ['2', '0.0411', '0.0413', 'GLYPH<0> 0.4599', '0.0413', '0.0414', 'GLYPH<0> 0.1935', '0.0417', '0.0414', '0.8462', '0.0417', '0.0414', '0.6396'], ['3', '0.0355', '0.0361', 'GLYPH<0> 1.5257', '0.0333', '0.0361', 'GLYPH<0> 7.6454', '0.0359', '0.0361', 'GLYPH<0> 0.5160', '0.0358', '0.0363', 'GLYPH<0> 1.1500'], ['4', '0.0343', '0.0339', '1.1799', '0.0341', '0.0340', '0.3826', '0.0337', '0.0339', 'GLYPH<0> 0.5257', '0.0344', '0.0342', '0.4999'], ['5', '0.0331', '0.0330', '0.1818', '0.0310', '0.0331', 'GLYPH<0> 6.3123', '0.0327', '0.0329', 'GLYPH<0> 0.8288', '0.0336', '0.0334', '0.5088'], ['6', '0.0330', '0.0327', '0.9471', '0.0331', '0.0328', '0.7004', '0.0328', '0.0326', '0.4842', '0.0334', '0.0332', '1.4496'], ['8', '0.0339', '0.0331', '2.4501', '0.0330', '0.0332', 'GLYPH<0> 0.5723', '0.0336', '0.0329', '2.2151', '0.0340', '0.0336', '1.0850'], ['9', '0.0337', '0.0334', '0.8373', '0.0343', '0.0336', '2.0833', '0.0336', '0.0333', '1.0126', '0.0345', '0.0341', '1.2353'], ['10', '0.0342', '0.0339', '0.8850', '0.0346', '0.0341', '1.6143', '0.0340', '0.0337', '0.6702', '0.0349', '0.0346', '0.9023'], ['12', '', '', '0.2292', '0.0352', '0.0351', '0.2849', '', '0.0347', '1.9741', '0.0365', '0.0357', '2.4215'], ['', '0.0350', '0.0349', '', '', '', '', '0.0354', '', '', '', '', ''], ['13', '0.0356', '0.0354', '0.3952', '0.0358', '0.0356', '0.4210', '0.0359', '0.0352', '1.8631', '', '0.0362', ''], ['14 15', '0.0368 0.0371', '0.0359 0.0365', '2.4207 1.6735', '0.0371 0.0369', '0.0362 0.0367', '2.6279 0.6819', '0.0362 0.0367', '0.0357 0.0362', '1.4646 1.2680', '0.0369 0.0373 0.0379', '0.0368 0.0373', '2.0392 1.4624 1.5671']]

,Glass.,Method.,Mass attenuation coefficient ( × 10 GLYPH<0> 2 cm 2 /g).662 KeV,Mass attenuation coefficient ( × 10 GLYPH<0> 2 cm 2 /g).1173 KeV,Mass attenuation coefficient ( × 10 GLYPH<0> 2 cm 2 /g).1332 KeV,Density (g/cm 3 ).
0,80TeO 2 - 15ZnO-5GeO 2,Geant4 XCOM,7.50 7.48,5.24 5.34,4.88 4.99,5.51
1,80TeO 2 - 15ZnO- 5Nb 2 O 5,Geant4,7.51,5.30,4.87,5.51
2,80TeO 2 - 15ZnO-5TiO,XCOM Geant4,7.49 7.50,5.35 5.34 5.36,4.99 4.93,5.47
3,80TeO 2 - 15ZnO-5WO 3,Geant4 XCOM,7.63 7.49,5.34 5.35,4.99 4.99,5.58
4,90TeO 2 - 10GeO 2 [32],XCOM Experimental,7.49 7.55,5.31 4.99,4.95 4.76,5.57
5,95TeO 2 - 5Nb 2 O 5 [32],XCOM Experimental,7.51,5.32,4.96,
6,90TeO 2 - 10WO 3 [32],XCOM,7.55 ± 0.29,5.12 ± 0.18,4.76 ± 0.18,5.52
7,90TeO 2 - 10ZnO [60],Experimental XCOM,7.76 7.79 ± 0.27 7.27,5.37 5.36 ± 0.18 5.32,5.00 4.99 ± 0.16 4.97,5.59
8,87.5TeO 2 - 12.5GeO 2 [62],Experimental Geant4,7.14 ± 0.13 7.57,5.22 ± 0.11 5.37,4.87 ± 0.10 4.96,5.05 5.28
9,90TeO 2 - 5GeO 2 - 5ZnO [9],Phy-X,7.81,5.41,5.02,5.48
10,80TeO 2 - 15ZnO - 5TiO 2 [65],ParShield,7.57,5.31,5.02,5.47

[['80TeO 2 - 15ZnO-5GeO 2', 'Geant4 XCOM', '7.50 7.48', '5.24 5.34', '4.88 4.99', '5.51'], ['80TeO 2 - 15ZnO- 5Nb 2 O 5', 'Geant4', '7.51', '5.30', '4.87', '5.51'], ['80TeO 2 - 15ZnO-5TiO', 'XCOM Geant4', '7.49 7.50', '5.35 5.34 5.36', '4.99 4.93', '5.47'], ['80TeO 2 - 15ZnO-5WO 3', 'Geant4 XCOM', '7.63 7.49', '5.34 5.35', '4.99 4.99', '5.58'], ['90TeO 2 - 10GeO 2 [32]', 'XCOM Experimental', '7.49 7.55', '5.31 4.99', '4.95 4.76', '5.57'], ['95TeO 2 - 5Nb 2 O 5 [32]', 'XCOM Experimental', '7.51', '5.32', '4.96', ''], ['90TeO 2 - 10WO 3 [32]', 'XCOM', '7.55 ± 0.29', '5.12 ± 0.18', '4.76 ± 0.18', '5.52'], ['90TeO 2 - 10ZnO [60]', 'Experimental XCOM', '7.76 7.79 ± 0.27 7.27', '5.37 5.36 ± 0.18 5.32', '5.00 4.99 ± 0.16 4.97', '5.59'], ['87.5TeO 2 - 12.5GeO 2 [62]', 'Experimental Geant4', '7.14 ± 0.13 7.57', '5.22 ± 0.11 5.37', '4.87 ± 0.10 4.96', '5.05 5.28'], ['90TeO 2 - 5GeO 2 - 5ZnO [9]', 'Phy-X', '7.81', '5.41', '5.02', '5.48'], ['80TeO 2 - 15ZnO - 5TiO 2 [65]', 'ParShield', '7.57', '5.31', '5.02', '5.47']]

       0                                                  1
0   [33]  M.T. Alabsy, M.A. Elzaher, Radiation shielding...
1   [34]  (2023) 7744, https://doi.org/10.1038/s41598-02...
2   [35]  org/10.1016/j.jallcom.2016.11.160. G.B. Cengiz...
3   [36]  539 - 553, https://doi.org/10.18038/estubtda.7...
4   [37]  10.1016/j.jnoncrysol.2021.121139. S.A. Issa, E...
5   [38]  org/10.1016/j.radphyschem.2015.11.025. U. Iliy...
6   [39]  N.T. El-Shamy, E.M. Mahrous, S.K. Alghamdi, M....
7   [40]  R. Siripuram, P.S.G. Rao, S. Sripada, Comparat...
8   [41]  K.I. Hussein, M.S. Alqahtani, K.J. Alzahrani, ...
9   [42]  ma15051844. R. Brückner, M. Tylkowski, L. Hupa...
10  [43]  J. Mater. Chem. B 4 (18) (2016) 3121 - 3134, h...
11  [44]  V.A.G. Rivera, I. Pinto, R. Falci, V. Fuertes,...
12  [45]  (2024) 173182, https://doi.org/10.1016/j.jallc...
13  [46]  10.1557/jmr.2013.341. Y. Rammah, M. Al-Buriahi...
14  [47]  physb.2019.411717. W. Abd-Allah, S. Marzouk, M...
15  [48]  46429 - 46439, https://doi.org/10.1016/j.ceram...
16  [49]  (2015) 20 - 30, https://doi.org/10.1016/j.soli...
17  [50]  doi.org/10.1038/srep18464. S. Stalin, A. Eduko...
18  [51]  S. Mansour, S. Wageh, M.F. Alotaibi, M. Abdo, ...
19  [52]  M. Mhareb, T. Ghrib, M. Sayyed, M.K. Hamad, N....
20  [53]  physb.2024.416221. G.G. Riungu, S.W. Mugo, J.M...

[['[33]', 'M.T. Alabsy, M.A. Elzaher, Radiation shielding performance of metal oxides/epdm rubber composites using geant4 simulation and computational study, Sci. Rep. 13'], ['[34]', '(2023) 7744, https://doi.org/10.1038/s41598-023-34615-9. M. Sayyed, S.I. Qashou, Z. Khattari, Radiation shielding competence of newly developed teo2-wo3 glasses, J. Alloys. Compd. 696 (2017) 632 - 638, https://doi.'], ['[35]', 'org/10.1016/j.jallcom.2016.11.160. G.B. Cengiz, ˙ I. Çaglar, ˘ G. Bilir, Gamma radiation shielding properties of natural glass obsidian, Eskiseh. Tech. Univ. J. Sci. Technol. - Appl. Sci. Eng. 21 (4) (2020)'], ['[36]', '539 - 553, https://doi.org/10.18038/estubtda.755217. ˙ I. Çaglar, ˘ G.B. Cengiz, G. Bilir, Gamma radiation shielding properties of some binary tellurite glasses, J. Non. Cryst. Solids. 574 (2021) 121139, https://doi.org/'], ['[37]', '10.1016/j.jnoncrysol.2021.121139. S.A. Issa, Effective atomic number and mass attenuation coefficient of PbO - BaO - B2O3 glass system, Radiat. Phys. Chem. 120 (2016) 33 - 37, https://doi.'], ['[38]', 'org/10.1016/j.radphyschem.2015.11.025. U. Iliyasu, M.S.M. Sanusi, N.E. Ahmad, The effect of WO 3 on the optical and radiation shielding properties of zinc-lead-borate glass, Radiat. Phys. Chem. 209 (2023) 111007, https://doi.org/10.1016/j.radphyschem.2023.111007.'], ['[39]', 'N.T. El-Shamy, E.M. Mahrous, S.K. Alghamdi, M.J. Tommalieh, H.M. Abomostafa, D.E. Abulyazied, E.A. Rabiea, A.S. Abouhaswa, A. Ismael, T.A.M. Taha, Synergistic effect of WO3 on structural, physical, optical, and dielectric characteristics of multicomponent borate glasses for optoelectronic applications, J. Mater. Res. Technol. 30 (2024) 7927 - 7937, https://doi.org/10.1016/j.jmrt.2024.05.164.'], ['[40]', 'R. Siripuram, P.S.G. Rao, S. Sripada, Comparative studies of structural and optical properties of Nb2O5 - Sb2O3 - TeO2 glass and glass-ceramics, Phys. Chem. Glas.: Eur. J. Glass Sci. Technol. B 63 (2022) 65 - 85, https://doi.org/10.13036/ 17533562.63.3.02.'], ['[41]', 'K.I. Hussein, M.S. Alqahtani, K.J. Alzahrani, F.F. Alqahtani, H.Y. Zahran, A. M. Alshehri, I.S. Yahia, M. Reben, E.S. Yousef, The effect of ZnO, MgO, TiO2, and Na2O modifiers on the physical, optical, and radiation shielding properties of a TeTaNb glass system, Mater 15 (5) (2022) 1844, https://doi.org/10.3390/'], ['[42]', 'ma15051844. R. Brückner, M. Tylkowski, L. Hupa, D.S. Brauer, Controlling the ion release from mixed alkali bioactive glasses by varying modifier ionic radii and molar volume,'], ['[43]', 'J. Mater. Chem. B 4 (18) (2016) 3121 - 3134, https://doi.org/10.1039/c5tb02426a. G. Guery, T. Cardinal, A. Fargues, V. Rodriguez, M. Dussauze, D. Cavagnat, P. Thomas, J. Cornette, P. Wachtel, J.D. Musgraves, K. Richardson, Influence of hydroxyl group on ir transparency of tellurite-based glasses, Int. J. Appl. Glass. Sci. 5 (2014) 178 - 184, https://doi.org/10.1111/ijag.12044.'], ['[44]', 'V.A.G. Rivera, I. Pinto, R. Falci, V. Fuertes, Y. Messaddeq, Novel insights into the electronic and optical properties of the 1.53- µ memission in Er3 + -doped oxide- and oxyfluoride- tellurite glasses for optical communications, J. Alloys. Compd. 976'], ['[45]', '(2024) 173182, https://doi.org/10.1016/j.jallcom.2023.173182. P. Joshi, B. Richards, A. Jha, Reduction of OH- ions in tellurite glasses using chlorine and oxygen gases, J. Mater. Res. 28 (2013) 3226 - 3233, https://doi.org/'], ['[46]', '10.1557/jmr.2013.341. Y. Rammah, M. Al-Buriahi, A. Abouhaswa, B2O3 - BaCO3 - Li2O3 glass system doped with Co3O4: structure, optical, and radiation shielding properties, Phys. B: Condens. Matter 576 (2020) 411717, https://doi.org/10.1016/j.'], ['[47]', 'physb.2019.411717. W. Abd-Allah, S. Marzouk, M. Gaafar, E. Salama, A closer look at the fabrication of some doped metal ions in borophosphate glass system and their structural, elastic, optical, and gamma-ray shielding characteristics, Ceram. Int. 50 (2024)'], ['[48]', '46429 - 46439, https://doi.org/10.1016/j.ceramint.2024.08.487. N. Ghribi, M. Dutreilh-Colas, J.-R. Ducl`ere, F. Gouraud, T. Chotard, R. Karray, A. Kabadou, P. Thomas, Structural, mechanical and optical investigations in the TeO2-rich part of the TeO2-GeO2-ZnO ternary glass system, Solid. State Sci. 40'], ['[49]', '(2015) 20 - 30, https://doi.org/10.1016/j.solidstatesciences.2014.12.009. V.A.G. Rivera, Y. Ledemi, M.A.Pereira-da Silva, Y. Messaddeq, E. Marega Jr, Plasmon-photon conversion to near-infrared emission from Yb3 + :(Au/Ag- nanoparticles) in tungsten-tellurite glasses, Sci. Rep. 6 (1) (2016) 18464, https://'], ['[50]', 'doi.org/10.1038/srep18464. S. Stalin, A. Edukondalu, M.A. Samee, C. Srinivasu, S. Rahman, Physical and optical investigations of Bi2O3-TeO2-B2O3-GeO2 glasses, Mater. Res. Express. 6 (2020) 125209, https://doi.org/10.1088/2053-1591/ab689c.'], ['[51]', 'S. Mansour, S. Wageh, M.F. Alotaibi, M. Abdo, M. Sadeq, Impact of bismuth oxide on the structure, optical features and ligand field parameters of borosilicate glasses doped with nickel oxide, Ceram. Int. 47 (2021), https://doi.org/10.1016/j. ceramint.2021.04.154.'], ['[52]', 'M. Mhareb, T. Ghrib, M. Sayyed, M.K. Hamad, N. Sfina, A.B. Ali, M. Almessiere, Structural, morphological, optical, and radiation shielding properties for BaO - TeO2 glass ceramic modified with different oxides: bi2O3, MoO3, MnO2, and TiO2, Phys. B: Condens. Matter 690 (2024) 416221, https://doi.org/10.1016/j.'], ['[53]', 'physb.2024.416221. G.G. Riungu, S.W. Mugo, J.M. Ngaruiya, G.M. John, N. Mugambi, Optical band energy, Urbach energy and associated band tails of nano crystalline TiO2 films at']]

,,"different annealing rates, Am. J. Nanosci. 7 (2021) 28, https://doi.org/10.11648/j."
0,[54],"ajn.20210701.15. M. Sayyed, M.J. Zaiter, M. Mh..."
1,[55],"M. Sayyed, A.A. Ati, M. Mhareb, K. Mahmoud, K...."
2,[56],"jallcom.2020.155668. J. Chacaliaza-Ricaldi, G...."
3,[57],"G. Lozano C ． , H. Benchorfi, M. Colas, Y. Mes..."
4,[58],"N. Jaba, A. Mermet, E. Duval, B. Champagnon, R..."
5,[59],https://doi.org/10.1016/j.jnoncrysol.2005.02.0...
6,[60],"M.R. Zaki, D. Hamani, M. Dutreilh-Colas, J.-R...."
7,[61],"J.L. Clabel H, G. Lozano C ． , E. Marega Jr, V..."
8,[62],"J. Chacaliaza-Ricaldi, V.A.G. Rivera, I. Pinto..."
9,[63],"jnoncrysol.2024.123063. A.A. Osipov, M. Liska,..."
10,[64],"S. Issa, M. Sayyed, M. Kurudirek, Investigatio..."
11,[65],"A.H. Almuqrin, M.I. Sayyed, Influence of ZnF2 ..."
12,[66],"N. Alfryyan, Z.A. Alrowaili, H.H. Somaily, I.O..."
13,[67],"M. Sayyed, K.M. Kaky, D. Gaikwad, O. Agar, U. ..."
14,[68],"S. Ravangvong, W. Nisspa, P. Glumglomchit, P. ..."
15,[69],"10584587.2021.1961522. M. Almatari, Gamma radi..."
16,[70],"N. Kaur, A. Khanna, M. Gonzalez-Barriuso, ´ F...."
17,[71],"jnoncrysol.2015.09.005. K.I. Hussein, M.S. Alq..."
18,[72],"P. Kaur, K. Singh, S. Thakur, P. Singh, B. Baj..."
19,[73],"I.I. Bashter, Calculation of radiation attenua..."

[['[54]', 'ajn.20210701.15. M. Sayyed, M.J. Zaiter, M. Mhareb, K. Mahmoud, S. Biradar, R.I. Mahdi, K. M. Kaky, Optical, physical, mechanical, structural, and radiation shielding investigations of B2O3 - TeO2-GeO2-MgO-PbO for ionizing protection and optical transmission application, Opt Mater 154 (2024) 115807, https://doi.org/10.1016/ j.optmat.2024.115807.'], ['[55]', 'M. Sayyed, A.A. Ati, M. Mhareb, K. Mahmoud, K.M. Kaky, S. Baki, M. Mahdi, Novel tellurite glass (60-x)TeO2 - 10GeO2 -20ZnO - 10BaO xBi2O3 for radiation shielding, J. Alloys. Compd. 844 (2020) 155668, https://doi.org/10.1016/j.'], ['[56]', 'jallcom.2020.155668. J. Chacaliaza-Ricaldi, G. Lozano C ． , J.L. Clabel H, F. Ferri, A. Rodrigues, Y. Messaddeq, V. Rivera, E. Marega Jr., Influence of Pr3 + ions on the structural properties of Er3 + -doped tellurite-tungsten glasses, J. Non. Cryst. Solids. 616 (2023) 122471, https://doi.org/10.1016/j.jnoncrysol.2023.122471.'], ['[57]', 'G. Lozano C ． , H. Benchorfi, M. Colas, Y. Messaddeq, G. Delaizir, V.A.G. Rivera, Boson peak preservation in tellurite glasses polymorphism, Ceram. Int. 50 (1) (2023) 5, https://doi.org/10.1016/j.ceramint.2023.10.114.'], ['[58]', 'N. Jaba, A. Mermet, E. Duval, B. Champagnon, Raman spectroscopy studies of Er3 + -doped zinc tellurite glasses, J. NonCrystalline Solids 351 (2005) 833 - 837,'], ['[59]', 'https://doi.org/10.1016/j.jnoncrysol.2005.02.003. A. Jha, B. Richards, G. Jose, T. Teddy-Fernandez, P. Joshi, X. Jiang, J. Lousteau, Rare-earth ion doped TeO2 and GeO2 glasses as laser materials, Prog. Mater. Sci. 57 (2012) 1426 - 1491, https://doi.org/10.1016/j.pmatsci.2012.04.003.'], ['[60]', 'M.R. Zaki, D. Hamani, M. Dutreilh-Colas, J.-R. Ducllere, ` O. Masson, P. Thomas, Synthesis, thermal, structural and linear optical properties of new glasses within the TeO2-TiO2-WO3 system, J. NonCrystalline Solids 484 (2018) 139148, https:// doi.org/10.1016/j.jnoncrysol.2018.01.034.'], ['[61]', 'J.L. Clabel H, G. Lozano C ． , E. Marega Jr, V. Rivera, et al., XPS analysis of bridging and non-bridging oxygen in Yb3 + -Er3 + -Tm3 + -doped zinc-tellurite glasses, J. Non. Cryst. Solids 553 (2021) 120520, https://doi.org/10.1016/j. jnoncrysol.2020.120520.'], ['[62]', 'J. Chacaliaza-Ricaldi, V.A.G. Rivera, I. Pinto, Y. Messaddeq, E. Marega, Germanate- tellurite glasses with low Er3 + ions concentration and their radiative emissions, J. Non. Cryst. Solids. 638 (2024) 123063, https://doi.org/10.1016/j.'], ['[63]', 'jnoncrysol.2024.123063. A.A. Osipov, M. Liska, ˇ L.M. Osipova, M. Chromcikova, ˇ ´ B. Hruska, ˇ Thermodynamic modeling and raman spectroscopy study of Na2O-TiO2-SiO2 glasses, Vib. Spectrosc. 111 (2020) 103160, https://doi.org/10.1016/j.vibspec.2020.103160.'], ['[64]', 'S. Issa, M. Sayyed, M. Kurudirek, Investigation of gamma radiation shielding properties of some zinc tellurite glasses, J. Phys. Sci. 27 (2016) 97 - 119, https:// doi.org/10.21315/jps2016.27.3.7.'], ['[65]', 'A.H. Almuqrin, M.I. Sayyed, Influence of ZnF2 and WO3 on radiation attenuation features of oxyfluoride tellurite WO3-ZnF2-TeO2 glasses using Phy-X/PSD software, Mater 15 (2022) 2285, https://doi.org/10.3390/ma15062285.'], ['[66]', 'N. Alfryyan, Z.A. Alrowaili, H.H. Somaily, I.O. Olarinoye, N. Alwadai, C. Mutuwong, M.S. Al-Buriahi, Comparison of radiation shielding and elastic properties of germinate tellurite glasses with the addition of Ga2O3, J. Taibah Univ. Sci. 16 (2022) 183 - 192, https://doi.org/10.1080/16583655.2022.2038468.'], ['[67]', 'M. Sayyed, K.M. Kaky, D. Gaikwad, O. Agar, U. Gawai, S. Baki, Physical, structural, optical and gamma radiation shielding properties of borate glasses containing heavy metals (Bi2O3/MoO3), J. Non. Cryst. Solids. 507 (2019) 30 - 37, https://doi. org/10.1016/j.jnoncrysol.2018.12.010.'], ['[68]', 'S. Ravangvong, W. Nisspa, P. Glumglomchit, P. Amornsophon, R. Kanuenghet, P. Pakdeepensuk, K. Sriwongsa, C. Khobkham, J. Kaewkhao, Effects of WO3 on radiation shielding properties of WO3 - TeO2 binary tellurite glass system, Integr. Ferroelectr. 222 (2022) 125 - 135, https://doi.org/10.1080/'], ['[69]', '10584587.2021.1961522. M. Almatari, Gamma radiation shielding properties of glasses within the TeO2- TiO2-ZnO system, Radiochim. Acta 107 (2019) 517 - 522, https://doi.org/10.1515/ ract-2018-3058.'], ['[70]', 'N. Kaur, A. Khanna, M. Gonzalez-Barriuso, ´ F. Gonzalez, ´ B. Chen, Effects of Al3 + , W6 + , Nb5 + and Pb2 + on the structure and properties of borotellurite glasses, J. Non. Cryst. Solids. 429 (2015) 153 - 163, https://doi.org/10.1016/j.'], ['[71]', 'jnoncrysol.2015.09.005. K.I. Hussein, M.S. Alqahtani, A.A. Meshawi, K.J. Alzahrani, H.Y. Zahran, A. M. Alshehri, I.S. Yahia, M. Reben, E.S. Yousef, Evaluation of the radiation shielding properties of a tellurite glass system modified with sodium oxide, Mater 15 (9) (2022) 3172, https://doi.org/10.3390/ma15093172.'], ['[72]', 'P. Kaur, K. Singh, S. Thakur, P. Singh, B. Bajwa, Investigation of bismuth borate glass system modified with barium for structural and gamma-ray shielding properties, Spectrochim. Acta A: Mol. Biomol. Spectrosc. 206 (2019) 367 - 377,'], ['[73]', 'I.I. Bashter, Calculation of radiation attenuation coefficients for shielding concretes, Ann. Nucl. Energy 24 (1997) 1389 - 1401, https://doi.org/10.1016/ S0306-4549(97)00003-0.']]